<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheelchair">

  <!-- ===================== -->
  <!-- PARAMETERS -->
  <!-- ===================== -->

  <xacro:property name="wheel_radius" value="0.16"/>
  <xacro:property name="wheel_width" value="0.06"/>
  <xacro:property name="wheel_separation" value="0.56"/>

  <xacro:property name="base_length" value="0.9"/>
  <xacro:property name="base_width" value="0.6"/>
  <xacro:property name="base_height" value="0.25"/>

  <xacro:property name="base_mass" value="105.0"/>
  <xacro:property name="wheel_mass" value="2.0"/>

  <xacro:property name="wheel_mu1" value="1.0"/>
  <xacro:property name="wheel_mu2" value="1.0"/>

  <!-- ===================== -->
  <!-- INERTIA MACRO -->
  <!-- ===================== -->

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia
      ixx="${m*(3*r*r + h*h)/12}"
      ixy="0" ixz="0"
      iyy="${m*(3*r*r + h*h)/12}"
      iyz="0"
      izz="${m*r*r/2}"/>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia
      ixx="${m*(y*y + z*z)/12}"
      ixy="0" ixz="0"
      iyy="${m*(x*x + z*z)/12}"
      iyz="0"
      izz="${m*(x*x + y*y)/12}"/>
  </xacro:macro>

  <!-- ===================== -->
  <!-- BASE -->
  <!-- ===================== -->

  <link name="base_footprint"/>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <xacro:box_inertia
        m="${base_mass}"
        x="${base_length}"
        y="${base_width}"
        z="${base_height}"/>
    </inertial>
  </link>

  <!-- ===================== -->
  <!-- YOUR WHEEL MACRO (UNCHANGED) -->
  <!-- ===================== -->

  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel_link">

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia
          m="${wheel_mass}"
          r="${wheel_radius}"
          h="${wheel_width}"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="0 ${reflect * wheel_separation/2} 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
    </joint>

    <gazebo reference="${prefix}_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000</kp>
      <kd>100</kd>
    </gazebo>
  </xacro:macro>

  <!-- ===================== -->
  <!-- INSTANTIATE WHEELS -->
  <!-- ===================== -->

  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>

  <!-- ===================== -->
  <!-- DIFF DRIVE PLUGIN -->
  <!-- ===================== -->

  <gazebo>
    <plugin
      filename="gz-sim-diff-drive-system"
      name="gz::sim::systems::DiffDrive">

      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>

      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>

      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>

      <max_linear_velocity>1.5</max_linear_velocity>
      <min_linear_velocity>-1.5</min_linear_velocity>
      <max_angular_velocity>1.0</max_angular_velocity>
      <min_angular_velocity>-1.0</min_angular_velocity>
    </plugin>
  </gazebo>

</robot>
